server:
  port: 9003
spring:
  application:
    name: member-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.255.132
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql://192.168.255.132:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
