server:
  port: 9003
spring:
  application:
    name: search-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.255.132
        username: nacos
        password: nacos
  elasticsearch:
    uris: http://192.168.255.132:9200