server:
  port: 9002
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.255.132
        username: nacos
        password: nacos
  application:
    name: authorizes-service
  redis:
    host: 192.168.255.132
    port: 6379
    password: 123456